import { AntdRegistry } from "@ant-design/nextjs-registry";
import { UiProvider } from "@repo/ui";
import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/*
          AntdRegistry 负责在 SSR 阶段收集 antd 的 cssinjs 样式并写进 HTML，
          否则样式只能在客户端注入，首屏会闪一下。
          UiProvider 提供统一的主题与 locale（来自 @repo/ui）。

          新应用接入时必须两个都加：只加 UiProvider 会样式闪烁，只加 AntdRegistry 则拿不到主题。
        */}
        <AntdRegistry>
          <UiProvider>{children}</UiProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
